import os
import json
import logging
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from typing import List
from dotenv import load_dotenv
import httpx
from google import genai
from google.genai import types

# Load environment variables from .env
load_dotenv()

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

app = FastAPI(title="Unified ML Classification Service")

# Read Tailscale LLM base URL from environment
LLM_API_BASE_URL = os.getenv("LLM_API_BASE_URL", "http://100.115.248.49:9292")
MODEL_NAME = os.getenv("LLM_MODEL_NAME", "qwen2.5-math-7b-instruct")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

class ClassifyRequest(BaseModel):
    question_text: str = Field(..., description="The calculus question text")
    choice_a: str = Field(..., description="Choice A")
    choice_b: str = Field(..., description="Choice B")
    choice_c: str = Field(..., description="Choice C")
    choice_d: str = Field(..., description="Choice D")
    choice_e: str = Field(..., description="Choice E")

class ClassifyResponse(BaseModel):
    main_topic: str
    skill_tags: List[str]
    bloom_level: str
    difficulty: float

@app.post("/api/v1/classify", response_model=ClassifyResponse)
async def classify_question(request: ClassifyRequest):
    """
    Handle topic tagging, skill extraction, bloom taxonomy, and difficulty scoring
    via the Hybrid Pipeline (Remote Lab PC + Cloud Gemini).
    """
    # ---------------------------------------------------------
    # STEP 1: The Solver (Lab PC via HTTPX)
    # ---------------------------------------------------------
    system_prompt_qwen = "You are an Expert Calculus Professor. Solve mathematical problems step-by-step. Show all working in Thai with LaTeX."
    user_prompt_qwen = f"แก้โจทย์ทีละขั้นตอน อย่างละเอียด\n\nโจทย์: {request.question_text}"

    payload_qwen = {
        "model": MODEL_NAME,
        "messages": [
            {"role": "system", "content": system_prompt_qwen},
            {"role": "user", "content": user_prompt_qwen}
        ],
        "temperature": 0.0
    }

    url_qwen = f"{LLM_API_BASE_URL}/v1/chat/completions"

    async with httpx.AsyncClient(timeout=180.0) as client:
        try:
            response = await client.post(url_qwen, json=payload_qwen)
            response.raise_for_status()
        except (httpx.ConnectError, httpx.TimeoutException) as e:
            error_msg = f"CRITICAL: Cannot reach the Remote Lab PC at {LLM_API_BASE_URL}. Ensure Tailscale is connected and the remote LLM is bound to 0.0.0.0."
            logger.error(error_msg)
            raise HTTPException(status_code=503, detail=error_msg)
        except httpx.HTTPStatusError as e:
            logger.error(f"HTTP error from Remote LLM: {e}")
            raise HTTPException(status_code=502, detail="Bad gateway or error from Remote LLM.")
        except Exception as e:
            logger.error(f"Unexpected error calling Remote LLM: {e}")
            raise HTTPException(status_code=500, detail="Internal server error.")

    data_qwen = response.json()
    try:
        correct_reasoning = data_qwen.get("choices", [{}])[0].get("message", {}).get("content", "")
    except Exception as e:
        logger.error(f"Failed to parse Qwen response: {e}")
        raise HTTPException(status_code=500, detail="Failed to parse Lab PC response.")

    # ---------------------------------------------------------
    # STEP 2: The Formatter (Cloud Gemini)
    # ---------------------------------------------------------
    if not GEMINI_API_KEY:
        raise HTTPException(status_code=500, detail="GEMINI_API_KEY is missing.")

    try:
        gemini_client = genai.Client(api_key=GEMINI_API_KEY)
        
        system_instruction_gemini = "You are a Master Calculus Educator and Assessment Data Extractor. Your task is to output strictly valid JSON matching the requested schema containing difficulty, main_topic, skill_tags, and bloom_level."
        
        user_prompt_gemini = f"""[QUESTION]
{request.question_text}

[CHOICES]
A) {request.choice_a}
B) {request.choice_b}
C) {request.choice_c}
D) {request.choice_d}
E) {request.choice_e}

[CORRECT SOLUTION (Generated by AI)]
{correct_reasoning}

Output ONLY a JSON object matching exactly this schema:
{{
  "main_topic": "string",
  "skill_tags": ["string", "string"],
  "bloom_level": "string",
  "difficulty": 0.5
}}"""

        # Ensure we use an async-compatible flow if we wanted to avoid blocking,
        # but the standard genai sync client generates content reliably here.
        gemini_response = gemini_client.models.generate_content(
            model='gemini-2.5-flash',
            contents=user_prompt_gemini,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction_gemini,
                response_mime_type="application/json",
                temperature=0.0,
            )
        )
        
        raw_json = gemini_response.text.strip()
        parsed_json = json.loads(raw_json)
        return ClassifyResponse(**parsed_json)
        
    except json.JSONDecodeError as e:
        logger.error(f"Failed to decode JSON from Gemini response: {e}\nRaw Content: {raw_json}")
        raise HTTPException(status_code=500, detail="Gemini returned invalid JSON format.")
    except Exception as e:
        logger.error(f"Error during Gemini processing: {e}")
        raise HTTPException(status_code=500, detail=f"Gemini processing failed: {str(e)}")
