"""update_tables

Revision ID: 0a0ca8311677
Revises: ec0f3e2585ee
Create Date: 2026-03-11 00:12:00.625947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a0ca8311677'
down_revision: Union[str, Sequence[str], None] = 'ec0f3e2585ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('default_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_error_codes_code'), 'error_codes', ['code'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_id'), 'quiz_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('bkt_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('quiz_attempt_id', sa.Integer(), nullable=False),
    sa.Column('skill_tag', sa.String(), nullable=False),
    sa.Column('p_prior', sa.Float(), nullable=False),
    sa.Column('p_posterior', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bkt_results_created_at'), 'bkt_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_bkt_results_id'), 'bkt_results', ['id'], unique=False)
    op.create_index(op.f('ix_bkt_results_quiz_attempt_id'), 'bkt_results', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_bkt_results_user_id'), 'bkt_results', ['user_id'], unique=False)
    op.drop_index(op.f('ix_ibkt_results_created_at'), table_name='ibkt_results')
    op.drop_index(op.f('ix_ibkt_results_id'), table_name='ibkt_results')
    op.drop_index(op.f('ix_ibkt_results_quiz_attempt_id'), table_name='ibkt_results')
    op.drop_index(op.f('ix_ibkt_results_user_id'), table_name='ibkt_results')
    op.drop_table('ibkt_results')
    op.drop_column('questions', 'guessing')
    op.add_column('quiz_attempts', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('error_code', sa.String(), nullable=True))
    op.add_column('quiz_attempts', sa.Column('error_category', sa.String(), nullable=True))
    op.create_index(op.f('ix_quiz_attempts_question_id'), 'quiz_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_session_id'), 'quiz_attempts', ['session_id'], unique=False)
    op.create_foreign_key(None, 'quiz_attempts', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quiz_attempts', 'quiz_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quiz_attempts', 'error_codes', ['error_code'], ['code'], ondelete='SET NULL')
    op.create_index(op.f('ix_recommendations_question_id'), 'recommendations', ['question_id'], unique=False)
    op.create_foreign_key(None, 'recommendations', 'questions', ['question_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recommendations', type_='foreignkey')
    op.drop_index(op.f('ix_recommendations_question_id'), table_name='recommendations')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_constraint(None, 'quiz_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_quiz_attempts_session_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_question_id'), table_name='quiz_attempts')
    op.drop_column('quiz_attempts', 'error_category')
    op.drop_column('quiz_attempts', 'error_code')
    op.drop_column('quiz_attempts', 'session_id')
    op.add_column('questions', sa.Column('guessing', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('ibkt_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_tag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('p_prior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('p_posterior', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('quiz_attempt_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], name=op.f('ibkt_results_quiz_attempt_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('ibkt_results_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ibkt_results_pkey'))
    )
    op.create_index(op.f('ix_ibkt_results_user_id'), 'ibkt_results', ['user_id'], unique=False)
    op.create_index(op.f('ix_ibkt_results_quiz_attempt_id'), 'ibkt_results', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_ibkt_results_id'), 'ibkt_results', ['id'], unique=False)
    op.create_index(op.f('ix_ibkt_results_created_at'), 'ibkt_results', ['created_at'], unique=False)
    op.drop_index(op.f('ix_bkt_results_user_id'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_quiz_attempt_id'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_id'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_created_at'), table_name='bkt_results')
    op.drop_table('bkt_results')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_error_codes_code'), table_name='error_codes')
    op.drop_table('error_codes')
    # ### end Alembic commands ###
