"""Add student_stats and update enums

Revision ID: 497d0541bff6
Revises: f7e8d9c0b1a2
Create Date: 2026-05-05 22:49:04.868349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '497d0541bff6'
down_revision: Union[str, Sequence[str], None] = 'f7e8d9c0b1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_mastery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_profile', sa.String(), nullable=True),
    sa.Column('avg_mastery', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_stats_id'), 'student_stats', ['id'], unique=False)
    op.create_index(op.f('ix_student_stats_last_updated'), 'student_stats', ['last_updated'], unique=False)
    op.create_index(op.f('ix_student_stats_user_id'), 'student_stats', ['user_id'], unique=True)
    op.create_table('bkt_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_attempt_id', sa.Integer(), nullable=False),
    sa.Column('skill_tag', sa.String(), nullable=False),
    sa.Column('p_prior', sa.Float(), nullable=False),
    sa.Column('p_posterior', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bkt_results_created_at'), 'bkt_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_bkt_results_id'), 'bkt_results', ['id'], unique=False)
    op.create_index(op.f('ix_bkt_results_quiz_attempt_id'), 'bkt_results', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_bkt_results_skill_tag'), 'bkt_results', ['skill_tag'], unique=False)
    op.drop_index(op.f('ix_student_knowledge_id'), table_name='student_knowledge')
    op.drop_index(op.f('ix_student_knowledge_last_updated'), table_name='student_knowledge')
    op.drop_index(op.f('ix_student_knowledge_user_id'), table_name='student_knowledge')
    op.drop_table('student_knowledge')
    # Create Enum types manually as Alembic autogenerate might miss them
    maintopic = postgresql.ENUM('LIMIT', 'DIFFERENTIAL', 'INTEGRAL', 'APPLICATIONS', name='maintopic')
    maintopic.create(op.get_bind(), checkfirst=True)
    
    subtopic = postgresql.ENUM('LIMIT_LAWS', 'CONTINUITY', 'DERIVATIVE_RULES', 'INTEGRATION_BY_PARTS', 'OTHER', 
                               'CURVE_SKETCHING', 'ADV_DERIVATIVE_RULES', 'INDEFINITE_INTEGRALS', 'APPLICATIONS', 
                               'AREA_VOLUME', 'PRODUCT_RULE', 'CHAIN_RULE', 'DEF_DERIVATIVE', 'EVALUATING_LIMITS', 
                               'SECOND_DERIVATIVE', 'KINEMATICS', 'DEFINITE_INTEGRALS', 'INVERSE_FUNCTIONS', 'LIMITS_INFINITY', 
                               name='subtopic')
    subtopic.create(op.get_bind(), checkfirst=True)

    # Map existing data to new Enums
    op.alter_column('questions', 'main_topic',
               existing_type=sa.VARCHAR(),
               type_=maintopic,
               postgresql_using="""
                   CASE 
                       WHEN main_topic = 'limits_and_continuity' THEN 'LIMIT'::maintopic 
                       WHEN main_topic = 'derivatives' THEN 'DIFFERENTIAL'::maintopic 
                       WHEN main_topic = 'integrals' THEN 'INTEGRAL'::maintopic 
                       WHEN main_topic = 'applications' THEN 'APPLICATIONS'::maintopic
                       ELSE 'LIMIT'::maintopic 
                   END
               """,
               existing_nullable=True)
    
    op.alter_column('questions', 'sub_topic',
               existing_type=sa.VARCHAR(),
               type_=subtopic,
               postgresql_using="""
                   CASE 
                       WHEN sub_topic = 'curve_sketching_analysis' THEN 'CURVE_SKETCHING'::subtopic
                       WHEN sub_topic = 'advanced_derivative_rules' THEN 'ADV_DERIVATIVE_RULES'::subtopic
                       WHEN sub_topic = 'indefinite_integrals' THEN 'INDEFINITE_INTEGRALS'::subtopic
                       WHEN sub_topic = 'applications' THEN 'APPLICATIONS'::subtopic
                       WHEN sub_topic = 'area_and_volume' THEN 'AREA_VOLUME'::subtopic
                       WHEN sub_topic = 'product_rule' THEN 'PRODUCT_RULE'::subtopic
                       WHEN sub_topic = 'continuity' THEN 'CONTINUITY'::subtopic
                       WHEN sub_topic = 'chain_rule' THEN 'CHAIN_RULE'::subtopic
                       WHEN sub_topic = 'definition_of_derivative' THEN 'DEF_DERIVATIVE'::subtopic
                       WHEN sub_topic = 'evaluating_limits' THEN 'EVALUATING_LIMITS'::subtopic
                       WHEN sub_topic = 'second_derivative' THEN 'SECOND_DERIVATIVE'::subtopic
                       WHEN sub_topic = 'kinematics' THEN 'KINEMATICS'::subtopic
                       WHEN sub_topic = 'definite_integrals' THEN 'DEFINITE_INTEGRALS'::subtopic
                       WHEN sub_topic = 'inverse_functions' THEN 'INVERSE_FUNCTIONS'::subtopic
                       WHEN sub_topic = 'limits_at_infinity' THEN 'LIMITS_INFINITY'::subtopic
                       ELSE 'OTHER'::subtopic
                   END
               """,
               existing_nullable=True)
    op.create_index(op.f('ix_questions_bloom_level'), 'questions', ['bloom_level'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.drop_column('quiz_attempts', 'error_category')
    op.drop_column('quiz_attempts', 'difficulty')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'avg_mastery')
    op.drop_column('users', 'current_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_profile', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('avg_mastery', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('quiz_attempts', sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('quiz_attempts', sa.Column('error_category', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('ix_questions_bloom_level'), table_name='questions')
    op.alter_column('questions', 'sub_topic',
               existing_type=sa.Enum('LIMIT_LAWS', 'CONTINUITY', 'DERIVATIVE_RULES', 'INTEGRATION_BY_PARTS', 'OTHER', 'CURVE_SKETCHING', 'ADV_DERIVATIVE_RULES', 'INDEFINITE_INTEGRALS', 'APPLICATIONS', 'AREA_VOLUME', 'PRODUCT_RULE', 'CHAIN_RULE', 'DEF_DERIVATIVE', 'EVALUATING_LIMITS', 'SECOND_DERIVATIVE', 'KINEMATICS', 'DEFINITE_INTEGRALS', 'INVERSE_FUNCTIONS', 'LIMITS_INFINITY', name='subtopic'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('questions', 'main_topic',
               existing_type=sa.Enum('LIMIT', 'DIFFERENTIAL', 'INTEGRAL', 'APPLICATIONS', name='maintopic'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.create_table('student_knowledge',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_mastery', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('student_knowledge_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_knowledge_pkey'))
    )
    op.create_index(op.f('ix_student_knowledge_user_id'), 'student_knowledge', ['user_id'], unique=True)
    op.create_index(op.f('ix_student_knowledge_last_updated'), 'student_knowledge', ['last_updated'], unique=False)
    op.create_index(op.f('ix_student_knowledge_id'), 'student_knowledge', ['id'], unique=False)
    op.drop_index(op.f('ix_bkt_results_skill_tag'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_quiz_attempt_id'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_id'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_created_at'), table_name='bkt_results')
    op.drop_table('bkt_results')
    op.drop_index(op.f('ix_student_stats_user_id'), table_name='student_stats')
    op.drop_index(op.f('ix_student_stats_last_updated'), table_name='student_stats')
    op.drop_index(op.f('ix_student_stats_id'), table_name='student_stats')
    op.drop_table('student_stats')
    # ### end Alembic commands ###
