"""Rename exam_attempts to quiz_attempts

Revision ID: 4d9609d1beba
Revises: fa092e5e3c84
Create Date: 2025-12-13 19:55:00.993100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""Rename exam_attempts to quiz_attempts

Revision ID: 4d9609d1beba
Revises: fa092e5e3c84
Create Date: 2025-12-13 19:55:00.993100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d9609d1beba'
down_revision: Union[str, Sequence[str], None] = 'fa092e5e3c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # STEP 1: Drop ALL foreign key constraints that reference tables we want to drop
    op.drop_constraint('exam_attempts_exam_id_fkey', 'exam_attempts', type_='foreignkey')
    op.drop_constraint('recommendations_exam_id_fkey', 'recommendations', type_='foreignkey')
    op.drop_constraint('ibkt_results_exam_attempt_id_fkey', 'ibkt_results', type_='foreignkey')
    
    # STEP 2: Create new quiz_attempts table
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('skill_tag', sa.String(), nullable=True),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_attempted_at'), 'quiz_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    
    # STEP 3: Now safe to drop exams table (no FK constraints pointing to it)
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_table('exams')
    
    # STEP 4: Drop old exam_attempts table (no FK constraints pointing to it now)
    op.drop_index(op.f('ix_exam_attempts_attempted_at'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_exam_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_id'), table_name='exam_attempts')
    op.drop_index(op.f('ix_exam_attempts_user_id'), table_name='exam_attempts')
    op.drop_table('exam_attempts')
    
    # STEP 5: Update ibkt_results to reference quiz_attempts
    op.add_column('ibkt_results', sa.Column('quiz_attempt_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_ibkt_results_exam_attempt_id'), table_name='ibkt_results')
    op.create_index(op.f('ix_ibkt_results_quiz_attempt_id'), 'ibkt_results', ['quiz_attempt_id'], unique=False)
    op.create_foreign_key(None, 'ibkt_results', 'quiz_attempts', ['quiz_attempt_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ibkt_results', 'exam_attempt_id')
    
    # STEP 6: Update recommendations (remove exam_id, add question_id)
    op.add_column('recommendations', sa.Column('question_id', sa.Integer(), nullable=True))
    op.drop_column('recommendations', 'exam_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommendations', sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('recommendations_exam_id_fkey'), 'recommendations', 'exams', ['exam_id'], ['id'], ondelete='CASCADE')
    op.drop_column('recommendations', 'question_id')
    op.add_column('ibkt_results', sa.Column('exam_attempt_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ibkt_results', type_='foreignkey')
    op.create_foreign_key(op.f('ibkt_results_exam_attempt_id_fkey'), 'ibkt_results', 'exam_attempts', ['exam_attempt_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_ibkt_results_quiz_attempt_id'), table_name='ibkt_results')
    op.create_index(op.f('ix_ibkt_results_exam_attempt_id'), 'ibkt_results', ['exam_attempt_id'], unique=False)
    op.drop_column('ibkt_results', 'quiz_attempt_id')
    op.create_table('exam_attempts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('exam_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('skill_tag', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_answer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('attempted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], name=op.f('exam_attempts_exam_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('exam_attempts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('exam_attempts_pkey'))
    )
    op.create_index(op.f('ix_exam_attempts_user_id'), 'exam_attempts', ['user_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_id'), 'exam_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_exam_id'), 'exam_attempts', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_attempts_attempted_at'), 'exam_attempts', ['attempted_at'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difficulty_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bloom_level', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('exams_pkey'))
    )
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_attempted_at'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
