"""initial_schema

Revision ID: 5a90ada55088
Revises: 
Create Date: 2026-06-14 15:01:56.073368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a90ada55088'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_codes',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('default_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index(op.f('ix_error_codes_code'), 'error_codes', ['code'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.Column('choices', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('discrimination', sa.Float(), nullable=True),
    sa.Column('bloom_level', sa.String(), nullable=True),
    sa.Column('main_topic', sa.Enum('LIMIT', 'DIFFERENTIAL', 'INTEGRAL', 'APPLICATIONS', name='maintopic'), nullable=True),
    sa.Column('sub_topic', sa.Enum('LIMIT_LAWS', 'EVALUATING_LIMITS', 'ALGEBRAIC_LIMITS', 'LIMITS_INFINITY', 'TRIG_LIMITS', 'CONTINUITY', 'DEF_DERIVATIVE', 'DERIVATIVE_RULES', 'PRODUCT_RULE', 'CHAIN_RULE', 'ADV_DERIVATIVE_RULES', 'IMPLICIT_DIFF', 'IMPLICIT_FUNCTIONS', 'SECOND_DERIVATIVE', 'HIGHER_ORDER_DERIV', 'APP_OF_DERIVATIVES', 'CURVE_SKETCHING', 'OPTIMIZATION', 'RELATED_RATES', 'KINEMATICS', 'INDEFINITE_INTEGRALS', 'DEFINITE_INTEGRALS', 'INTEGRATION_TECHNIQUES', 'SUBSTITUTION', 'INTEGRATION_BY_PARTS', 'ADV_INTEGRATION', 'AREA_VOLUME', 'TRIG_FUNCTIONS', 'TRIG_IDENTITIES', 'INVERSE_FUNCTIONS', 'APPLICATIONS', 'OTHER', name='subtopic'), nullable=True),
    sa.Column('skill_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_bloom_level'), 'questions', ['bloom_level'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_main_topic'), 'questions', ['main_topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_id'), 'quiz_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_created_at'), 'recommendations', ['created_at'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_question_id'), 'recommendations', ['question_id'], unique=False)
    op.create_index(op.f('ix_recommendations_user_id'), 'recommendations', ['user_id'], unique=False)
    op.create_table('student_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('skill_mastery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_profile', sa.String(), nullable=True),
    sa.Column('avg_mastery', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_stats_id'), 'student_stats', ['id'], unique=False)
    op.create_index(op.f('ix_student_stats_last_updated'), 'student_stats', ['last_updated'], unique=False)
    op.create_index(op.f('ix_student_stats_user_id'), 'student_stats', ['user_id'], unique=True)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('skill_tag', sa.String(), nullable=True),
    sa.Column('user_answer', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('attempted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['error_code'], ['error_codes.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_attempts_attempted_at'), 'quiz_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_id'), 'quiz_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_question_id'), 'quiz_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_session_id'), 'quiz_attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('bkt_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_attempt_id', sa.Integer(), nullable=False),
    sa.Column('skill_tag', sa.String(), nullable=False),
    sa.Column('p_prior', sa.Float(), nullable=False),
    sa.Column('p_posterior', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bkt_results_created_at'), 'bkt_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_bkt_results_id'), 'bkt_results', ['id'], unique=False)
    op.create_index(op.f('ix_bkt_results_quiz_attempt_id'), 'bkt_results', ['quiz_attempt_id'], unique=False)
    op.create_index(op.f('ix_bkt_results_skill_tag'), 'bkt_results', ['skill_tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bkt_results_skill_tag'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_quiz_attempt_id'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_id'), table_name='bkt_results')
    op.drop_index(op.f('ix_bkt_results_created_at'), table_name='bkt_results')
    op.drop_table('bkt_results')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_session_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_question_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_attempted_at'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_student_stats_user_id'), table_name='student_stats')
    op.drop_index(op.f('ix_student_stats_last_updated'), table_name='student_stats')
    op.drop_index(op.f('ix_student_stats_id'), table_name='student_stats')
    op.drop_table('student_stats')
    op.drop_index(op.f('ix_recommendations_user_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_question_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_created_at'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_questions_main_topic'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index(op.f('ix_questions_bloom_level'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_error_codes_code'), table_name='error_codes')
    op.drop_table('error_codes')
    # ### end Alembic commands ###
